language: elixir
elixir:
  - 1.7.4
  - 1.8.1
otp_release:
  - 20.3
  - 21.3
env:
  - MIX_ENV=test
before_script:
  - mix local.hex --force
  - mix deps.get
  - for dir in ./extensions/*; do ( cd "$dir" && mix deps.get ); done
script:
  - mix test --trace --include deprecations
  - mix format --check-formatted
  - mix dialyzer --halt-exit-status
  - for dir in ./extensions/*; do ( cd "$dir" && mix test ); done
  - for dir in ./extensions/*; do ( cd "$dir" && mix format --check-formatted ); done
cache:
  directories:
    - _build
before_cache:
  # should only keep the dialyzer artifacts
  - mix clean
  - mix deps.clean --all
