language: elixir
elixir:
  - 1.7.2
otp_release:
  - 20.3
  - 21.0
env:
  - MIX_ENV=test
before_script:
  - mix local.hex --force && mix deps.get
script:
  - mix test
  - mix format --check-formatted
  - mix dialyzer --halt-exit-status
cache:
  - _build
before_cache:
  # should only keep the dialyzer artifacts
  - mix clean
  - mix deps.clean --all
  - tree _build
